# -*- coding: utf-8 -*-
"""Huffman Coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1CdKFIkivkD6qnLS_g-SNADs8mJ_Gxd
"""

# Get the input String
string =

# Create tree nodes
class NodeTree(object):

# Main function to implement huffman coding
def huffman_code_tree(node, left=True, binString=''):

# Calculate frequency of occurrence
freq = {}

# Print the characters and its huffmancode
huffmanCode = huffman_code_tree(nodes[0][0])

print(' Char | Huffman code ')